version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "develop"
    schedule:
      # interval: "weekly"
      # day: "wednesday"
      interval: "daily"
      time: "09:00"
    reviewers:
      - "maboa"
    assignees:
      - "Laurian"
    labels:
      - "npm"
      - "dependencies"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    # open-pull-requests-limit: 0
