version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/website"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "maboa"
    assignees:
      - "Laurian"
    labels:
      - "npm"
      - "dependencies"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/website/amplify/backend/function/datastream/src"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"
    assignees:
      - "Laurian"
    labels:
      - "npm"
      - "dependencies"
      - "backend"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/website/amplify/backend/function/eventstream/src"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"
    assignees:
      - "Laurian"
    labels:
      - "npm"
      - "dependencies"
      - "backend"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/website/amplify/backend/function/items/src"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"
    assignees:
      - "Laurian"
    labels:
      - "npm"
      - "dependencies"
      - "backend"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/website/amplify/backend/function/postauth/src"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"
    assignees:
      - "Laurian"
    labels:
      - "npm"
      - "dependencies"
      - "backend"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/website/amplify/backend/function/probe/src"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"
    assignees:
      - "Laurian"
    labels:
      - "npm"
      - "dependencies"
      - "backend"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/website/amplify/backend/function/transcode/src"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"
    assignees:
      - "Laurian"
    labels:
      - "npm"
      - "dependencies"
      - "backend"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/website/amplify/backend/function/transcribe/src"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"
    assignees:
      - "Laurian"
    labels:
      - "npm"
      - "dependencies"
      - "backend"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "pip"
    directory: "/website/amplify/backend/function/ytdl"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"
    assignees:
      - "Laurian"
    labels:
      - "pip"
      - "dependencies"
      - "backend"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/packages/remixer"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "maboa"
      - "Laurian"
    assignees:
      - "piotrf"
    labels:
      - "npm"
      - "dependencies"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/packages/storybook"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "Laurian"
    assignees:
      - "piotrf"
    labels:
      - "npm"
      - "dependencies"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
